services:
  fan-controller:
    build: ./app
    container_name: fan_controller
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    privileged: true
    devices:
      - /dev/i2c-1:/dev/i2c-1
    volumes:
      - ./data:/app/data
      - /sys/class/gpio:/sys/class/gpio
      - /sys/class/pwm:/sys/class/pwm

  api:
    build: ./api
    container_name: fan_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./data:/app/data
