services:
  fan-controller:
    build: ./app
    container_name: fan_controller
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    privileged: true # Für GPIO + I2C Zugriff
    devices:
      - /dev/i2c-1:/dev/i2c-1 # I2C für BME280
    volumes:
      - ./data:/app/data # Daten persistent
